let obj0 = {
  dateForm: "2023-03-30T18:10:44",
  dateIppv: null,
  dateOpNpf: null,
  dateOpPoyavDor: "2023-03-30T18:10:00",
  dateOtm: "0001-01-01T00:00:00",
  datePerevGar: null,
  datePriemDor: null,
  datePriemGos: null,
  datePsPoezd: null,
  dateSnyatGar: null,
  dateSppv: null,
  dorPriemGos: 0,
  dorSdach: 12,
  dorSdachGos: 0,
  dvs: "2023-03-30T19:58:33",
  dvsT: "2023-03-30T19:58:33",
  famagentPriem: "",
  famagentSdach: "",
  idDis: 2362,
  idDorDis: 4,
  idDorPriemGos: 0,
  idDorRasch: 4,
  idDorSdach: 5,
  idDorSdachGos: 0,
  idPark: 0,
  idPoezdCjs: 0,
  idPoezdRasp: 1041913787,
  idPoezdS1: 0,
  idPoezdS2: 0,
  idPoezdS3: 0,
  idPoezdS4: 0,
  idPrognStykSdach: 2759,
  idPut: 0,
  idPutPeregOtpr: -1,
  idPutPeregPrib: -1,
  idPutTra: 0,
  idSobyt: "1b7acd28-cf1c-11ed-a81d-3df880fb7b16",
  idSobytOtm: "00000000-0000-0000-0000-000000000000",
  idSobytPred: "85c26753-cf1b-11ed-a81d-d7ac2c3e0847",
  idSortS: 0,
  idStanGarObsl: 0,
  idStanGarObsln: 0,
  idStanIppv: 0,
  idStanNaprOtpr: 2421,
  idStanNaprPrib: 0,
  idStanNpf: 0,
  idStanOp: 2362,
  idStanPriem: 0,
  idStanPriemPogran: 0,
  idStanSdach: 0,
  idStanSdachPogran: 0,
  idStanSppv: 0,
  idStansGarObsln: 0,
  idStykPpv: 0,
  idStykPriemDor: 0,
  idStykPriemGos: 0,
  indNegab: "0000",
  indexPoezd: "100001324170004",
  indexPoezdS1: "000000000000000",
  indexPoezdS2: "000000000000000",
  indexPoezdS3: "000000000000000",
  indexPoezdS4: "000000000000000",
  kds: "0200",
  kdsT: "0200",
  kodDorDis: 10,
  kodDorRasch: 10,
  kodNar: 0,
  kodOpDop: "000",
  kodOpOsn: "002",
  kodPrichBros: 0,
  kodPrikr: "5",
  kodSortS: 0,
  kodStanNaprOtpr: 102100,
  kodStanNaprPrib: 0,
  kodStanOp: 100001,
  kodVp: "-",
  kolOsey: 280,
  kolSutOpozd: 0,
  kolVag: 66,
  kolVagGruz: 66,
  kolVagNpf: 0,
  kolVagUch: 66,
  kopNpf: "0",
  kopPoyavDor: "5",
  kpp: "910000007",
  kppT: "910000007",
  kskmPoezd: 170004,
  ksnmPoezd: 100001,
  nomGolVag: "91646695",
  nomPark: 2,
  nomPoezd: 2858,
  nomPpv: 0,
  nomPut: 11,
  nomPutPeregOtpr: 0,
  nomPutPeregPrib: 0,
  nomPutTra: 0,
  nomSost: 324,
  nomXvVag: "75036749",
  ogrSkor: 0,
  otklNormTn: 955,
  otklNormVag: 18,
  otmGivn: "0",
  otmMarsh: "0",
  prBros: "0",
  prDogMarsch: "0",
  prGrupVag: "1",
  prIzmIp: "0",
  prKommGrz: "0",
  prKontPoezd: "0",
  prKontrel: "0",
  prKorTek: "0",
  prKp: "0",
  prKtk: "1",
  prMarshOv: "0",
  prMmo: "0",
  prNalDlb: "-",
  prNarSxp: "0",
  prNpfIst: "0",
  prNpfTek: "0",
  prObmenaPpv: "0",
  prOoSpecGrz: "0",
  prOpasGrz: "1",
  prOperZamen: "-",
  prOtcep: "0",
  prOtm: "0",
  prOxr: "0",
  prPerevorot: "-",
  prPoezdRf: "1",
  prPorvag: "1",
  prPorvagCs: "1",
  prPorvagKr: "0",
  prPorvagPl: "0",
  prPorvagPr: "0",
  prPorvagPv: "0",
  prPorvagRf: "0",
  prPriemDor: "0",
  prPriemZagran: "0",
  prPrioritet: "0",
  prRazv: "0",
  prRf: "0",
  prSdachDor: "0",
  prSdachZagran: "0",
  prSkoropGrz: "0",
  prSledPrikaz: "0",
  prSnyatGar: "0",
  prSoed: "0",
  prSoglPpv: "0",
  prSp5: "0",
  prSpecGrz: "0",
  prStk: "0",
  prVagEdv: "1",
  prVagFgp: "0",
  prVagKonSled: "1",
  prVagNkachnom: "0",
  prVagPz: "0",
  prVagZagran: "0",
  prognStykSdach: 124307,
  rodPoezd: 10,
  stanGarObsl: 0,
  stanGarObsln: 0,
  stanIppv: 0,
  stanNpf: 0,
  stanPriem: 0,
  stanPriemPogran: 0,
  stanSdach: 0,
  stanSdachPogran: 0,
  stanSppv: 0,
  stansGarObsln: 0,
  stykPpv: 0,
  stykPriemDor: 0,
  stykPriemGos: 0,
  tipInfPoezd: "1",
  tipPpv: "0",
  uslDlPoezd: 75,
  vesBr: 4045,
  vesNet: 2133,
  vesTarCent: 1912,
  vidOtklNorm: 6,
};

let obj1 = {
  dateForm: "",
  dateIppv: "",
  dateOpNpf: "",
  dateOpPoyavDor: "",
  dateOtm: "",
  datePerevGar: "",
  datePriemDor: "",
  datePriemGos: "",
  datePsPoezd: "",
  dateSnyatGar: "",
  dateSppv: "",
  dorPriemGos: "",
  dorSdach: "",
  dorSdachGos: "",
  dvs: "",
  dvsT: "",
  famagentPriem: "",
  famagentSdach: "",
  idDis: "",
  idDorDis: "",
  idDorPriemGos: "",
  idDorRasch: "",
  idDorSdach: "",
  idDorSdachGos: "",
  idPark: "",
  idPoezdCjs: "",
  idPoezdRasp: "",
  idPoezdS1: "",
  idPoezdS2: "",
  idPoezdS3: "",
  idPoezdS4: "",
  idPrognStykSdach: "",
  idPut: "",
  idPutPeregOtpr: "",
  idPutPeregPrib: "",
  idPutTra: "",
  idSobyt: "",
  idSobytOtm: "",
  idSobytPred: "",
  idSortS: "",
  idStanGarObsl: "",
  idStanGarObsln: "",
  idStanIppv: "",
  idStanNaprOtpr: "",
  idStanNaprPrib: "",
  idStanNpf: "",
  idStanOp: "",
  idStanPriem: "",
  idStanPriemPogran: "",
  idStanSdach: "",
  idStanSdachPogran: "",
  idStanSppv: "",
  idStansGarObsln: "",
  idStykPpv: "",
  idStykPriemDor: "",
  idStykPriemGos: "",
  indNegab: "",
  indexPoezd: "",
  indexPoezdS1: "",
  indexPoezdS2: "",
  indexPoezdS3: "",
  indexPoezdS4: "",
  kds: "",
  kdsT: "",
  kodDorDis: "",
  kodDorRasch: "",
  kodNar: "",
  kodOpDop: "",
  kodOpOsn: "",
  kodPrichBros: "",
  kodPrikr: "",
  kodSortS: "",
  kodStanNaprOtpr: "",
  kodStanNaprPrib: "",
  kodStanOp: "",
  kodVp: "",
  kolOsey: "",
  kolSutOpozd: "",
  kolVag: "",
  kolVagGruz: "",
  kolVagNpf: "",
  kolVagUch: "",
  kopNpf: "",
  kopPoyavDor: "",
  kpp: "",
  kppT: "",
  kskmPoezd: "",
  ksnmPoezd: "",
  nomGolVag: "",
  nomPark: "",
  nomPoezd: "",
  nomPpv: "",
  nomPut: "",
  nomPutPeregOtpr: "",
  nomPutPeregPrib: "",
  nomPutTra: "",
  nomSost: "",
  nomXvVag: "",
  ogrSkor: "",
  otklNormTn: "",
  otklNormVag: "",
  otmGivn: "",
  otmMarsh: "",
  prBros: "",
  prDogMarsch: "",
  prGrupVag: "",
  prIzmIp: "",
  prKommGrz: "",
  prKontPoezd: "",
  prKontrel: "",
  prKorTek: "",
  prKp: "",
  prKtk: "",
  prMarshOv: "",
  prMmo: "",
  prNalDlb: "",
  prNarSxp: "",
  prNpfIst: "",
  prNpfTek: "",
  prObmenaPpv: "",
  prOoSpecGrz: "",
  prOpasGrz: "",
  prOperZamen: "",
  prOtcep: "",
  prOtm: "",
  prOxr: "",
  prPerevorot: "",
  prPoezdRf: "",
  prPorvag: "",
  prPorvagCs: "",
  prPorvagKr: "",
  prPorvagPl: "",
  prPorvagPr: "",
  prPorvagPv: "",
  prPorvagRf: "",
  prPriemDor: "",
  prPriemZagran: "",
  prPrioritet: "",
  prRazv: "",
  prRf: "",
  prSdachDor: "",
  prSdachZagran: "",
  prSkoropGrz: "",
  prSledPrikaz: "",
  prSnyatGar: "",
  prSoed: "",
  prSoglPpv: "",
  prSp5: "",
  prSpecGrz: "",
  prStk: "",
  prVagEdv: "",
  prVagFgp: "",
  prVagKonSled: "",
  prVagNkachnom: "",
  prVagPz: "",
  prVagZagran: "",
  prognStykSdach: "",
  rodPoezd: "",
  stanGarObsl: "",
  stanGarObsln: "",
  stanIppv: "",
  stanNpf: "",
  stanPriem: "",
  stanPriemPogran: "",
  stanSdach: "",
  stanSdachPogran: "",
  stanSppv: "",
  stansGarObsln: "",
  stykPpv: "",
  stykPriemDor: "",
  stykPriemGos: "",
  tipInfPoezd: "",
  tipPpv: "",
  uslDlPoezd: "",
  vesBr: "",
  vesNet: "",
  vesTarCent: "",
  vidOtklNorm: "",
};

let obj2 = {
  dateForm: "",
  dateIppv: "",
  dateOpNpf: "",
  dateOpPoyavDor: "",
  dateOtm: "",
  datePerevGar: "",
  datePriemDor: "",
  datePriemGos: "",
  datePsPoezd: "",
  dateSnyatGar: "",
  dateSppv: "",
  dorPriemGos: "",
  dorSdach: "",
  dorSdachGos: "",
  dvs: "",
  dvsT: "",
  famagentPriem: "",
  famagentSdach: "",
  idDis: "",
  idDorDis: "",
  idDorPriemGos: "",
  idDorRasch: "",
  idDorSdach: "",
  idDorSdachGos: "",
  idPark: "",
  idPoezdCjs: "",
  idPoezdRasp: "",
  idPoezdS1: "",
  idPoezdS2: "",
  idPoezdS3: "",
  idPoezdS4: "",
  idPrognStykSdach: "",
  idPut: "",
  idPutPeregOtpr: "",
  idPutPeregPrib: "",
  idPutTra: "",
  idSobyt: "",
  idSobytOtm: "",
  idSobytPred: "",
  idSortS: "",
  idStanGarObsl: "",
  idStanGarObsln: "",
  idStanIppv: "",
  idStanNaprOtpr: "",
  idStanNaprPrib: "",
  idStanNpf: "",
  idStanOp: "",
  idStanPriem: "",
  idStanPriemPogran: "",
  idStanSdach: "",
  idStanSdachPogran: "",
  idStanSppv: "",
  idStansGarObsln: "",
  idStykPpv: "",
  idStykPriemDor: "",
  idStykPriemGos: "",
  indNegab: "",
  indexPoezd: "",
  indexPoezdS1: "",
  indexPoezdS2: "",
  indexPoezdS3: "",
  indexPoezdS4: "",
  kds: "",
  kdsT: "",
  kodDorDis: "",
  kodDorRasch: "",
  kodNar: "",
  kodOpDop: "",
  kodOpOsn: "",
  kodPrichBros: "",
  kodPrikr: "",
  kodSortS: "",
  kodStanNaprOtpr: "",
  kodStanNaprPrib: "",
  kodStanOp: "",
  kodVp: "",
  kolOsey: "",
  kolSutOpozd: "",
  kolVag: "",
  kolVagGruz: "",
  kolVagNpf: "",
  kolVagUch: "",
  kopNpf: "",
  kopPoyavDor: "",
  kpp: "",
  kppT: "",
  kskmPoezd: "",
  ksnmPoezd: "",
  nomGolVag: "",
  nomPark: "",
  nomPoezd: "",
  nomPpv: "",
  nomPut: "",
  nomPutPeregOtpr: "",
  nomPutPeregPrib: "",
  nomPutTra: "",
  nomSost: "",
  nomXvVag: "",
  ogrSkor: "",
  otklNormTn: "",
  otklNormVag: "",
  otmGivn: "",
  otmMarsh: "",
  prBros: "",
  prDogMarsch: "",
  prGrupVag: "",
  prIzmIp: "",
  prKommGrz: "",
  prKontPoezd: "",
  prKontrel: "",
  prKorTek: "",
  prKp: "",
  prKtk: "",
  prMarshOv: "",
  prMmo: "",
  prNalDlb: "",
  prNarSxp: "",
  prNpfIst: "",
  prNpfTek: "",
  prObmenaPpv: "",
  prOoSpecGrz: "",
  prOpasGrz: "",
  prOperZamen: "",
  prOtcep: "",
  prOtm: "",
  prOxr: "",
  prPerevorot: "",
  prPoezdRf: "",
  prPorvag: "",
  prPorvagCs: "",
  prPorvagKr: "",
  prPorvagPl: "",
  prPorvagPr: "",
  prPorvagPv: "",
  prPorvagRf: "",
  prPriemDor: "",
  prPriemZagran: "",
  prPrioritet: "",
  prRazv: "",
  prRf: "",
  prSdachDor: "",
  prSdachZagran: "",
  prSkoropGrz: "",
  prSledPrikaz: "",
  prSnyatGar: "",
  prSoed: "",
  prSoglPpv: "",
  prSp5: "",
  prSpecGrz: "",
  prStk: "",
  prVagEdv: "",
  prVagFgp: "",
  prVagKonSled: "",
  prVagNkachnom: "",
  prVagPz: "",
  prVagZagran: "",
  prognStykSdach: "",
  rodPoezd: "",
  stanGarObsl: "",
  stanGarObsln: "",
  stanIppv: "",
  stanNpf: "",
  stanPriem: "",
  stanPriemPogran: "",
  stanSdach: "",
  stanSdachPogran: "",
  stanSppv: "",
  stansGarObsln: "",
  stykPpv: "",
  stykPriemDor: "",
  stykPriemGos: "",
  tipInfPoezd: "",
  tipPpv: "",
  uslDlPoezd: "",
  vesBr: "",
  vesNet: "",
  vesTarCent: "",
  vidOtklNorm: "",
};

let obj3 = {
  dateForm: "",
  dateIppv: "",
  dateOpNpf: "",
  dateOpPoyavDor: "",
  dateOtm: "",
  datePerevGar: "",
  datePriemDor: "",
  datePriemGos: "",
  datePsPoezd: "",
  dateSnyatGar: "",
  dateSppv: "",
  dorPriemGos: "",
  dorSdach: "",
  dorSdachGos: "",
  dvs: "",
  dvsT: "",
  famagentPriem: "",
  famagentSdach: "",
  idDis: "",
  idDorDis: "",
  idDorPriemGos: "",
  idDorRasch: "",
  idDorSdach: "",
  idDorSdachGos: "",
  idPark: "",
  idPoezdCjs: "",
  idPoezdRasp: "",
  idPoezdS1: "",
  idPoezdS2: "",
  idPoezdS3: "",
  idPoezdS4: "",
  idPrognStykSdach: "",
  idPut: "",
  idPutPeregOtpr: "",
  idPutPeregPrib: "",
  idPutTra: "",
  idSobyt: "",
  idSobytOtm: "",
  idSobytPred: "",
  idSortS: "",
  idStanGarObsl: "",
  idStanGarObsln: "",
  idStanIppv: "",
  idStanNaprOtpr: "",
  idStanNaprPrib: "",
  idStanNpf: "",
  idStanOp: "",
  idStanPriem: "",
  idStanPriemPogran: "",
  idStanSdach: "",
  idStanSdachPogran: "",
  idStanSppv: "",
  idStansGarObsln: "",
  idStykPpv: "",
  idStykPriemDor: "",
  idStykPriemGos: "",
  indNegab: "",
  indexPoezd: "",
  indexPoezdS1: "",
  indexPoezdS2: "",
  indexPoezdS3: "",
  indexPoezdS4: "",
  kds: "",
  kdsT: "",
  kodDorDis: "",
  kodDorRasch: "",
  kodNar: "",
  kodOpDop: "",
  kodOpOsn: "",
  kodPrichBros: "",
  kodPrikr: "",
  kodSortS: "",
  kodStanNaprOtpr: "",
  kodStanNaprPrib: "",
  kodStanOp: "",
  kodVp: "",
  kolOsey: "",
  kolSutOpozd: "",
  kolVag: "",
  kolVagGruz: "",
  kolVagNpf: "",
  kolVagUch: "",
  kopNpf: "",
  kopPoyavDor: "",
  kpp: "",
  kppT: "",
  kskmPoezd: "",
  ksnmPoezd: "",
  nomGolVag: "",
  nomPark: "",
  nomPoezd: "",
  nomPpv: "",
  nomPut: "",
  nomPutPeregOtpr: "",
  nomPutPeregPrib: "",
  nomPutTra: "",
  nomSost: "",
  nomXvVag: "",
  ogrSkor: "",
  otklNormTn: "",
  otklNormVag: "",
  otmGivn: "",
  otmMarsh: "",
  prBros: "",
  prDogMarsch: "",
  prGrupVag: "",
  prIzmIp: "",
  prKommGrz: "",
  prKontPoezd: "",
  prKontrel: "",
  prKorTek: "",
  prKp: "",
  prKtk: "",
  prMarshOv: "",
  prMmo: "",
  prNalDlb: "",
  prNarSxp: "",
  prNpfIst: "",
  prNpfTek: "",
  prObmenaPpv: "",
  prOoSpecGrz: "",
  prOpasGrz: "",
  prOperZamen: "",
  prOtcep: "",
  prOtm: "",
  prOxr: "",
  prPerevorot: "",
  prPoezdRf: "",
  prPorvag: "",
  prPorvagCs: "",
  prPorvagKr: "",
  prPorvagPl: "",
  prPorvagPr: "",
  prPorvagPv: "",
  prPorvagRf: "",
  prPriemDor: "",
  prPriemZagran: "",
  prPrioritet: "",
  prRazv: "",
  prRf: "",
  prSdachDor: "",
  prSdachZagran: "",
  prSkoropGrz: "",
  prSledPrikaz: "",
  prSnyatGar: "",
  prSoed: "",
  prSoglPpv: "",
  prSp5: "",
  prSpecGrz: "",
  prStk: "",
  prVagEdv: "",
  prVagFgp: "",
  prVagKonSled: "",
  prVagNkachnom: "",
  prVagPz: "",
  prVagZagran: "",
  prognStykSdach: "",
  rodPoezd: "",
  stanGarObsl: "",
  stanGarObsln: "",
  stanIppv: "",
  stanNpf: "",
  stanPriem: "",
  stanPriemPogran: "",
  stanSdach: "",
  stanSdachPogran: "",
  stanSppv: "",
  stansGarObsln: "",
  stykPpv: "",
  stykPriemDor: "",
  stykPriemGos: "",
  tipInfPoezd: "",
  tipPpv: "",
  uslDlPoezd: "",
  vesBr: "",
  vesNet: "",
  vesTarCent: "",
  vidOtklNorm: "",
};

let obj4 = {
  dateForm: "",
  dateIppv: "",
  dateOpNpf: "",
  dateOpPoyavDor: "",
  dateOtm: "",
  datePerevGar: "",
  datePriemDor: "",
  datePriemGos: "",
  datePsPoezd: "",
  dateSnyatGar: "",
  dateSppv: "",
  dorPriemGos: "",
  dorSdach: "",
  dorSdachGos: "",
  dvs: "",
  dvsT: "",
  famagentPriem: "",
  famagentSdach: "",
  idDis: "",
  idDorDis: "",
  idDorPriemGos: "",
  idDorRasch: "",
  idDorSdach: "",
  idDorSdachGos: "",
  idPark: "",
  idPoezdCjs: "",
  idPoezdRasp: "",
  idPoezdS1: "",
  idPoezdS2: "",
  idPoezdS3: "",
  idPoezdS4: "",
  idPrognStykSdach: "",
  idPut: "",
  idPutPeregOtpr: "",
  idPutPeregPrib: "",
  idPutTra: "",
  idSobyt: "",
  idSobytOtm: "",
  idSobytPred: "",
  idSortS: "",
  idStanGarObsl: "",
  idStanGarObsln: "",
  idStanIppv: "",
  idStanNaprOtpr: "",
  idStanNaprPrib: "",
  idStanNpf: "",
  idStanOp: "",
  idStanPriem: "",
  idStanPriemPogran: "",
  idStanSdach: "",
  idStanSdachPogran: "",
  idStanSppv: "",
  idStansGarObsln: "",
  idStykPpv: "",
  idStykPriemDor: "",
  idStykPriemGos: "",
  indNegab: "",
  indexPoezd: "",
  indexPoezdS1: "",
  indexPoezdS2: "",
  indexPoezdS3: "",
  indexPoezdS4: "",
  kds: "",
  kdsT: "",
  kodDorDis: "",
  kodDorRasch: "",
  kodNar: "",
  kodOpDop: "",
  kodOpOsn: "",
  kodPrichBros: "",
  kodPrikr: "",
  kodSortS: "",
  kodStanNaprOtpr: "",
  kodStanNaprPrib: "",
  kodStanOp: "",
  kodVp: "",
  kolOsey: "",
  kolSutOpozd: "",
  kolVag: "",
  kolVagGruz: "",
  kolVagNpf: "",
  kolVagUch: "",
  kopNpf: "",
  kopPoyavDor: "",
  kpp: "",
  kppT: "",
  kskmPoezd: "",
  ksnmPoezd: "",
  nomGolVag: "",
  nomPark: "",
  nomPoezd: "",
  nomPpv: "",
  nomPut: "",
  nomPutPeregOtpr: "",
  nomPutPeregPrib: "",
  nomPutTra: "",
  nomSost: "",
  nomXvVag: "",
  ogrSkor: "",
  otklNormTn: "",
  otklNormVag: "",
  otmGivn: "",
  otmMarsh: "",
  prBros: "",
  prDogMarsch: "",
  prGrupVag: "",
  prIzmIp: "",
  prKommGrz: "",
  prKontPoezd: "",
  prKontrel: "",
  prKorTek: "",
  prKp: "",
  prKtk: "",
  prMarshOv: "",
  prMmo: "",
  prNalDlb: "",
  prNarSxp: "",
  prNpfIst: "",
  prNpfTek: "",
  prObmenaPpv: "",
  prOoSpecGrz: "",
  prOpasGrz: "",
  prOperZamen: "",
  prOtcep: "",
  prOtm: "",
  prOxr: "",
  prPerevorot: "",
  prPoezdRf: "",
  prPorvag: "",
  prPorvagCs: "",
  prPorvagKr: "",
  prPorvagPl: "",
  prPorvagPr: "",
  prPorvagPv: "",
  prPorvagRf: "",
  prPriemDor: "",
  prPriemZagran: "",
  prPrioritet: "",
  prRazv: "",
  prRf: "",
  prSdachDor: "",
  prSdachZagran: "",
  prSkoropGrz: "",
  prSledPrikaz: "",
  prSnyatGar: "",
  prSoed: "",
  prSoglPpv: "",
  prSp5: "",
  prSpecGrz: "",
  prStk: "",
  prVagEdv: "",
  prVagFgp: "",
  prVagKonSled: "",
  prVagNkachnom: "",
  prVagPz: "",
  prVagZagran: "",
  prognStykSdach: "",
  rodPoezd: "",
  stanGarObsl: "",
  stanGarObsln: "",
  stanIppv: "",
  stanNpf: "",
  stanPriem: "",
  stanPriemPogran: "",
  stanSdach: "",
  stanSdachPogran: "",
  stanSppv: "",
  stansGarObsln: "",
  stykPpv: "",
  stykPriemDor: "",
  stykPriemGos: "",
  tipInfPoezd: "",
  tipPpv: "",
  uslDlPoezd: "",
  vesBr: "",
  vesNet: "",
  vesTarCent: "",
  vidOtklNorm: "",
};

function changeKeys(obj) {
  for (let key in obj) {
    obj[key] = null;
  }
  return obj;
}

// console.log(changeKeys(obj4));

console.log(obj0);

let objNew = {
  idPoezd: 8709100,
  dateOp: "2023-06-28T12:00:00",
  idOp: 9011,
  dateForm: "",
  dateIppv: "",
  dateOpNpf: "",
  dateOpPoyavDor: "",
  dateOtm: "",
  datePerevGar: "",
  datePriemDor: "",
  datePriemGos: "",
  datePsPoezd: "",
  dateSnyatGar: "",
  dateSppv: "",
  dorPriemGos: "",
  dorSdach: "",
  dorSdachGos: "",
  dvs: "",
  dvsT: "",
  famagentPriem: "",
  famagentSdach: "",
  idDis: "",
  idDorDis: "",
  idDorPriemGos: "",
  idDorRasch: "",
  idDorSdach: "",
  idDorSdachGos: "",
  idPark: "",
  idPoezdCjs: "",
  idPoezdRasp: "",
  idPoezdS1: "",
  idPoezdS2: "",
  idPoezdS3: "",
  idPoezdS4: "",
  idPrognStykSdach: "",
  idPut: "",
  idPutPeregOtpr: "",
  idPutPeregPrib: "",
  idPutTra: "",
  idSobyt: "",
  idSobytOtm: "",
  idSobytPred: "",
  idSortS: "",
  idStanGarObsl: "",
  idStanGarObsln: "",
  idStanIppv: "",
  idStanNaprOtpr: "",
  idStanNaprPrib: "",
  idStanNpf: "",
  idStanOp: "",
  idStanPriem: "",
  idStanPriemPogran: "",
  idStanSdach: "",
  idStanSdachPogran: "",
  idStanSppv: "",
  idStansGarObsln: "",
  idStykPpv: "",
  idStykPriemDor: "",
  idStykPriemGos: "",
  indNegab: "",
  indexPoezd: "",
  indexPoezdS1: "",
  indexPoezdS2: "",
  indexPoezdS3: "",
  indexPoezdS4: "",
  kds: "",
  kdsT: "",
  kodDorDis: "",
  kodDorRasch: "",
  kodNar: "",
  kodOpDop: "",
  kodOpOsn: "",
  kodPrichBros: "",
  kodPrikr: "",
  kodSortS: "",
  kodStanNaprOtpr: "",
  kodStanNaprPrib: "",
  kodStanOp: "",
  kodVp: "",
  kolOsey: "",
  kolSutOpozd: "",
  kolVag: "",
  kolVagGruz: "",
  kolVagNpf: "",
  kolVagUch: "",
  kopNpf: "",
  kopPoyavDor: "",
  kpp: "",
  kppT: "",
  kskmPoezd: "",
  ksnmPoezd: "",
  nomGolVag: "",
  nomPark: "",
  nomPoezd: "",
  nomPpv: "",
  nomPut: "",
  nomPutPeregOtpr: "",
  nomPutPeregPrib: "",
  nomPutTra: "",
  nomSost: "",
  nomXvVag: "",
  ogrSkor: "",
  otklNormTn: "",
  otklNormVag: "",
  otmGivn: "",
  otmMarsh: "",
  prBros: "",
  prDogMarsch: "",
  prGrupVag: "",
  prIzmIp: "",
  prKommGrz: "",
  prKontPoezd: "",
  prKontrel: "",
  prKorTek: "",
  prKp: "",
  prKtk: "",
  prMarshOv: "",
  prMmo: "",
  prNalDlb: "",
  prNarSxp: "",
  prNpfIst: "",
  prNpfTek: "",
  prObmenaPpv: "",
  prOoSpecGrz: "",
  prOpasGrz: "",
  prOperZamen: "",
  prOtcep: "",
  prOtm: "",
  prOxr: "",
  prPerevorot: "",
  prPoezdRf: "",
  prPorvag: "",
  prPorvagCs: "",
  prPorvagKr: "",
  prPorvagPl: "",
  prPorvagPr: "",
  prPorvagPv: "",
  prPorvagRf: "",
  prPriemDor: "",
  prPriemZagran: "",
  prPrioritet: "",
  prRazv: "",
  prRf: "",
  prSdachDor: "",
  prSdachZagran: "",
  prSkoropGrz: "",
  prSledPrikaz: "",
  prSnyatGar: "",
  prSoed: "",
  prSoglPpv: "",
  prSp5: "",
  prSpecGrz: "",
  prStk: "",
  prVagEdv: "",
  prVagFgp: "",
  prVagKonSled: "",
  prVagNkachnom: "",
  prVagPz: "",
  prVagZagran: "",
  prognStykSdach: "",
  rodPoezd: "",
  stanGarObsl: "",
  stanGarObsln: "",
  stanIppv: "",
  stanNpf: "",
  stanPriem: "",
  stanPriemPogran: "",
  stanSdach: "",
  stanSdachPogran: "",
  stanSppv: "",
  stansGarObsln: "",
  stykPpv: "",
  stykPriemDor: "",
  stykPriemGos: "",
  tipInfPoezd: "",
  tipPpv: "",
  uslDlPoezd: "",
  vesBr: "",
  vesNet: "",
  vesTarCent: "",
  vidOtklNorm: "",
};

let objNew2 = {
  dateForm: " ",
  dateIppv: " ",
  dateOp: " ",
  dateOpNpf: " ",
  dateOpPoyavDor: " ",
  dateOtm: " ",
  datePerevGar: " ",
  datePriemDor: " ",
  datePriemGos: " ",
  datePsPoezd: " ",
  dateSnyatGar: " ",
  dateSppv: " ",
  dorPriemGos: " ",
  dorSdach: " ",
  dorSdachGos: " ",
  dvs: " ",
  dvsT: " ",
  famagentPriem: " ",
  famagentSdach: " ",
  idDis: " ",
  idDorDis: " ",
  idDorPriemGos: " ",
  idDorRasch: " ",
  idDorSdach: " ",
  idDorSdachGos: " ",
  idOp: " ",
  idPark: " ",
  idPoezd: " ",
  idPoezdCjs: " ",
  idPoezdRasp: " ",
  idPoezdS1: " ",
  idPoezdS2: " ",
  idPoezdS3: " ",
  idPoezdS4: " ",
  idPrognStykSdach: " ",
  idPut: " ",
  idPutPeregOtpr: " ",
  idPutPeregPrib: " ",
  idPutTra: " ",
  idSobyt: " ",
  idSobytOtm: " ",
  idSobytPred: " ",
  idSortS: " ",
  idStanGarObsl: " ",
  idStanGarObsln: " ",
  idStanIppv: " ",
  idStanNaprOtpr: " ",
  idStanNaprPrib: " ",
  idStanNpf: " ",
  idStanOp: " ",
  idStanPriem: " ",
  idStanPriemPogran: " ",
  idStanSdach: " ",
  idStanSdachPogran: " ",
  idStanSppv: " ",
  idStansGarObsln: " ",
  idStykPpv: " ",
  idStykPriemDor: " ",
  idStykPriemGos: " ",
  indNegab: " ",
  indexPoezd: " ",
  indexPoezdS1: " ",
  indexPoezdS2: " ",
  indexPoezdS3: " ",
  indexPoezdS4: " ",
  kds: " ",
  kdsT: " ",
  kodDorDis: " ",
  kodDorRasch: " ",
  kodNar: " ",
  kodOpDop: " ",
  kodOpOsn: " ",
  kodPrichBros: " ",
  kodPrikr: " ",
  kodSortS: " ",
  kodStanNaprOtpr: " ",
  kodStanNaprPrib: " ",
  kodStanOp: " ",
  kodVp: " ",
  kolOsey: " ",
  kolSutOpozd: " ",
  kolVag: " ",
  kolVagGruz: " ",
  kolVagNpf: " ",
  kolVagUch: " ",
  kopNpf: " ",
  kopPoyavDor: " ",
  kpp: " ",
  kppT: " ",
  kskmPoezd: " ",
  ksnmPoezd: " ",
  nomGolVag: " ",
  nomPark: " ",
  nomPoezd: " ",
  nomPpv: " ",
  nomPut: " ",
  nomPutPeregOtpr: " ",
  nomPutPeregPrib: " ",
  nomPutTra: " ",
  nomSost: " ",
  nomXvVag: " ",
  ogrSkor: " ",
  otklNormTn: " ",
  otklNormVag: " ",
  otmGivn: " ",
  otmMarsh: " ",
  prBros: " ",
  prDogMarsch: " ",
  prGrupVag: " ",
  prIzmIp: " ",
  prKommGrz: " ",
  prKontPoezd: " ",
  prKontrel: " ",
  prKorTek: " ",
  prKp: " ",
  prKtk: " ",
  prMarshOv: " ",
  prMmo: " ",
  prNalDlb: " ",
  prNarSxp: " ",
  prNpfIst: " ",
  prNpfTek: " ",
  prObmenaPpv: " ",
  prOoSpecGrz: " ",
  prOpasGrz: " ",
  prOperZamen: " ",
  prOtcep: " ",
  prOtm: " ",
  prOxr: " ",
  prPerevorot: " ",
  prPoezdRf: " ",
  prPorvag: " ",
  prPorvagCs: " ",
  prPorvagKr: " ",
  prPorvagPl: " ",
  prPorvagPr: " ",
  prPorvagPv: " ",
  prPorvagRf: " ",
  prPriemDor: " ",
  prPriemZagran: " ",
  prPrioritet: " ",
  prRazv: " ",
  prRf: " ",
  prSdachDor: " ",
  prSdachZagran: " ",
  prSkoropGrz: " ",
  prSledPrikaz: " ",
  prSnyatGar: " ",
  prSoed: " ",
  prSoglPpv: " ",
  prSp5: " ",
  prSpecGrz: " ",
  prStk: " ",
  prVagEdv: " ",
  prVagFgp: " ",
  prVagKonSled: " ",
  prVagNkachnom: " ",
  prVagPz: " ",
  prVagZagran: " ",
  prognStykSdach: " ",
  rodPoezd: " ",
  stanGarObsl: " ",
  stanGarObsln: " ",
  stanIppv: " ",
  stanNpf: " ",
  stanPriem: " ",
  stanPriemPogran: " ",
  stanSdach: " ",
  stanSdachPogran: " ",
  stanSppv: " ",
  stansGarObsln: " ",
  stykPpv: " ",
  stykPriemDor: " ",
  stykPriemGos: " ",
  tipInfPoezd: " ",
  tipPpv: " ",
  uslDlPoezd: " ",
  vesBr: " ",
  vesNet: " ",
  vesTarCent: " ",
  vidOtklNorm: " ",
};

let objNew3 = {
  dateForm: "-",
  dateIppv: "-",
  dateOpNpf: "-",
  dateOpPoyavDor: "-",
  dateOtm: "-",
  datePerevGar: "-",
  datePriemDor: "-",
  datePriemGos: "-",
  datePsPoezd: "-",
  dateSnyatGar: "-",
  dateSppv: "-",
  dorPriemGos: "-",
  dorSdach: "-",
  dorSdachGos: "-",
  dvs: "-",
  dvsT: "-",
  famagentPriem: "-",
  famagentSdach: "-",
  idDis: "-",
  idDorDis: "-",
  idDorPriemGos: "-",
  idDorRasch: "-",
  idDorSdach: "-",
  idDorSdachGos: "-",
  idPark: "-",
  idPoezdCjs: "-",
  idPoezdRasp: "-",
  idPoezdS1: "-",
  idPoezdS2: "-",
  idPoezdS3: "-",
  idPoezdS4: "-",
  idPrognStykSdach: "-",
  idPut: "-",
  idPutPeregOtpr: "-",
  idPutPeregPrib: "-",
  idPutTra: "-",
  idSobyt: "-",
  idSobytOtm: "-",
  idSobytPred: "-",
  idSortS: "-",
  idStanGarObsl: "-",
  idStanGarObsln: "-",
  idStanIppv: "-",
  idStanNaprOtpr: "-",
  idStanNaprPrib: "-",
  idStanNpf: "-",
  idStanOp: "-",
  idStanPriem: "-",
  idStanPriemPogran: "-",
  idStanSdach: "-",
  idStanSdachPogran: "-",
  idStanSppv: "-",
  idStansGarObsln: "-",
  idStykPpv: "-",
  idStykPriemDor: "-",
  idStykPriemGos: "-",
  indNegab: "-",
  indexPoezd: "-",
  indexPoezdS1: "-",
  indexPoezdS2: "-",
  indexPoezdS3: "-",
  indexPoezdS4: "-",
  kds: "-",
  kdsT: "-",
  kodDorDis: "-",
  kodDorRasch: "-",
  kodNar: "-",
  kodOpDop: "-",
  kodOpOsn: "-",
  kodPrichBros: "-",
  kodPrikr: "-",
  kodSortS: "-",
  kodStanNaprOtpr: "-",
  kodStanNaprPrib: "-",
  kodStanOp: "-",
  kodVp: "-",
  kolOsey: "-",
  kolSutOpozd: "-",
  kolVag: "-",
  kolVagGruz: "-",
  kolVagNpf: "-",
  kolVagUch: "-",
  kopNpf: "-",
  kopPoyavDor: "-",
  kpp: "-",
  kppT: "-",
  kskmPoezd: "-",
  ksnmPoezd: "-",
  nomGolVag: "-",
  nomPark: "-",
  nomPoezd: "-",
  nomPpv: "-",
  nomPut: "-",
  nomPutPeregOtpr: "-",
  nomPutPeregPrib: "-",
  nomPutTra: "-",
  nomSost: "-",
  nomXvVag: "-",
  ogrSkor: "-",
  otklNormTn: "-",
  otklNormVag: "-",
  otmGivn: "-",
  otmMarsh: "-",
  prBros: "-",
  prDogMarsch: "-",
  prGrupVag: "-",
  prIzmIp: "-",
  prKommGrz: "-",
  prKontPoezd: "-",
  prKontrel: "-",
  prKorTek: "-",
  prKp: "-",
  prKtk: "-",
  prMarshOv: "-",
  prMmo: "-",
  prNalDlb: "-",
  prNarSxp: "-",
  prNpfIst: "-",
  prNpfTek: "-",
  prObmenaPpv: "-",
  prOoSpecGrz: "-",
  prOpasGrz: "-",
  prOperZamen: "-",
  prOtcep: "-",
  prOtm: "-",
  prOxr: "-",
  prPerevorot: "-",
  prPoezdRf: "-",
  prPorvag: "-",
  prPorvagCs: "-",
  prPorvagKr: "-",
  prPorvagPl: "-",
  prPorvagPr: "-",
  prPorvagPv: "-",
  prPorvagRf: "-",
  prPriemDor: "-",
  prPriemZagran: "-",
  prPrioritet: "-",
  prRazv: "-",
  prRf: "-",
  prSdachDor: "-",
  prSdachZagran: "-",
  prSkoropGrz: "-",
  prSledPrikaz: "-",
  prSnyatGar: "-",
  prSoed: "-",
  prSoglPpv: "-",
  prSp5: "-",
  prSpecGrz: "-",
  prStk: "-",
  prVagEdv: "-",
  prVagFgp: "-",
  prVagKonSled: "-",
  prVagNkachnom: "-",
  prVagPz: "-",
  prVagZagran: "-",
  prognStykSdach: "-",
  rodPoezd: "-",
  stanGarObsl: "-",
  stanGarObsln: "-",
  stanIppv: "-",
  stanNpf: "-",
  stanPriem: "-",
  stanPriemPogran: "-",
  stanSdach: "-",
  stanSdachPogran: "-",
  stanSppv: "-",
  stansGarObsln: "-",
  stykPpv: "-",
  stykPriemDor: "-",
  stykPriemGos: "-",
  tipInfPoezd: "-",
  tipPpv: "-",
  uslDlPoezd: "-",
  vesBr: "-",
  vesNet: "-",
  vesTarCent: "-",
  vidOtklNorm: "-",
};

let objNew4 = {
  dateForm: null,
  dateIppv: null,
  dateOpNpf: null,
  dateOpPoyavDor: null,
  dateOtm: null,
  datePerevGar: null,
  datePriemDor: null,
  datePriemGos: null,
  datePsPoezd: null,
  dateSnyatGar: null,
  dateSppv: null,
  dorPriemGos: null,
  dorSdach: null,
  dorSdachGos: null,
  dvs: null,
  dvsT: null,
  famagentPriem: null,
  famagentSdach: null,
  idDis: null,
  idDorDis: null,
  idDorPriemGos: null,
  idDorRasch: null,
  idDorSdach: null,
  idDorSdachGos: null,
  idPark: null,
  idPoezdCjs: null,
  idPoezdRasp: null,
  idPoezdS1: null,
  idPoezdS2: null,
  idPoezdS3: null,
  idPoezdS4: null,
  idPrognStykSdach: null,
  idPut: null,
  idPutPeregOtpr: null,
  idPutPeregPrib: null,
  idPutTra: null,
  idSobyt: null,
  idSobytOtm: null,
  idSobytPred: null,
  idSortS: null,
  idStanGarObsl: null,
  idStanGarObsln: null,
  idStanIppv: null,
  idStanNaprOtpr: null,
  idStanNaprPrib: null,
  idStanNpf: null,
  idStanOp: null,
  idStanPriem: null,
  idStanPriemPogran: null,
  idStanSdach: null,
  idStanSdachPogran: null,
  idStanSppv: null,
  idStansGarObsln: null,
  idStykPpv: null,
  idStykPriemDor: null,
  idStykPriemGos: null,
  indNegab: null,
  indexPoezd: null,
  indexPoezdS1: null,
  indexPoezdS2: null,
  indexPoezdS3: null,
  indexPoezdS4: null,
  kds: null,
  kdsT: null,
  kodDorDis: null,
  kodDorRasch: null,
  kodNar: null,
  kodOpDop: null,
  kodOpOsn: null,
  kodPrichBros: null,
  kodPrikr: null,
  kodSortS: null,
  kodStanNaprOtpr: null,
  kodStanNaprPrib: null,
  kodStanOp: null,
  kodVp: null,
  kolOsey: null,
  kolSutOpozd: null,
  kolVag: null,
  kolVagGruz: null,
  kolVagNpf: null,
  kolVagUch: null,
  kopNpf: null,
  kopPoyavDor: null,
  kpp: null,
  kppT: null,
  kskmPoezd: null,
  ksnmPoezd: null,
  nomGolVag: null,
  nomPark: null,
  nomPoezd: null,
  nomPpv: null,
  nomPut: null,
  nomPutPeregOtpr: null,
  nomPutPeregPrib: null,
  nomPutTra: null,
  nomSost: null,
  nomXvVag: null,
  ogrSkor: null,
  otklNormTn: null,
  otklNormVag: null,
  otmGivn: null,
  otmMarsh: null,
  prBros: null,
  prDogMarsch: null,
  prGrupVag: null,
  prIzmIp: null,
  prKommGrz: null,
  prKontPoezd: null,
  prKontrel: null,
  prKorTek: null,
  prKp: null,
  prKtk: null,
  prMarshOv: null,
  prMmo: null,
  prNalDlb: null,
  prNarSxp: null,
  prNpfIst: null,
  prNpfTek: null,
  prObmenaPpv: null,
  prOoSpecGrz: null,
  prOpasGrz: null,
  prOperZamen: null,
  prOtcep: null,
  prOtm: null,
  prOxr: null,
  prPerevorot: null,
  prPoezdRf: null,
  prPorvag: null,
  prPorvagCs: null,
  prPorvagKr: null,
  prPorvagPl: null,
  prPorvagPr: null,
  prPorvagPv: null,
  prPorvagRf: null,
  prPriemDor: null,
  prPriemZagran: null,
  prPrioritet: null,
  prRazv: null,
  prRf: null,
  prSdachDor: null,
  prSdachZagran: null,
  prSkoropGrz: null,
  prSledPrikaz: null,
  prSnyatGar: null,
  prSoed: null,
  prSoglPpv: null,
  prSp5: null,
  prSpecGrz: null,
  prStk: null,
  prVagEdv: null,
  prVagFgp: null,
  prVagKonSled: null,
  prVagNkachnom: null,
  prVagPz: null,
  prVagZagran: null,
  prognStykSdach: null,
  rodPoezd: null,
  stanGarObsl: null,
  stanGarObsln: null,
  stanIppv: null,
  stanNpf: null,
  stanPriem: null,
  stanPriemPogran: null,
  stanSdach: null,
  stanSdachPogran: null,
  stanSppv: null,
  stansGarObsln: null,
  stykPpv: null,
  stykPriemDor: null,
  stykPriemGos: null,
  tipInfPoezd: null,
  tipPpv: null,
  uslDlPoezd: null,
  vesBr: null,
  vesNet: null,
  vesTarCent: null,
  vidOtklNorm: null,
};
